#!/usr/bin/env sh

FILE=$(echo -n $BUILD_PATH | tail -c +2)

if [ -z "${DOCKER_TAG}" ]; then
  docker build --build-arg=COMMIT=$(git rev-parse --short HEAD) --build-arg=BRANCH=$SOURCE_BRANCH -t $IMAGE_NAME -f $FILE .
else
  docker build --build-arg=COMMIT=$(git rev-parse --short HEAD) --build-arg=BRANCH=$DOCKER_TAG -t $IMAGE_NAME -f $FILE .
fi
